CREATE TABLE utente (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codice_fiscale VARCHAR(255) NOT NULL,
    cognome VARCHAR(255),
    email VARCHAR(255),
    nome VARCHAR(255),
    password VARCHAR(255),
    ruolo VARCHAR(255),
    CONSTRAINT utente_codice_fiscale_key UNIQUE (codice_fiscale),
    CONSTRAINT utente_ruolo_check CHECK (ruolo IN ('DIPENDENTE', 'ADMIN'))
);

CREATE TABLE cliente (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(255),
    tariffa_oraria DOUBLE PRECISION NOT NULL
);

CREATE UNIQUE INDEX uk_cliente_nome_ci ON cliente (LOWER(nome));

CREATE TABLE timesheet (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    anno INTEGER NOT NULL,
    data_compilazione DATE,
    mese INTEGER NOT NULL,
    utente_id BIGINT NOT NULL,
    stato VARCHAR(255) NOT NULL,
    CONSTRAINT uk_timesheet_utente_mese_anno UNIQUE (utente_id, mese, anno),
    CONSTRAINT fk95s8h51nwdcysh9d8farhbfev FOREIGN KEY (utente_id) REFERENCES utente (id),
    CONSTRAINT timesheet_stato_check CHECK (stato IN ('APERTO', 'CONFERMATO', 'CHIUSO'))
);

CREATE TABLE timesheet_riga (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    costo_orario DOUBLE PRECISION NOT NULL,
    data DATE,
    minuti INTEGER NOT NULL,
    orario DOUBLE PRECISION NOT NULL,
    ore INTEGER NOT NULL,
    cliente_id BIGINT,
    timesheet_id BIGINT,
    CONSTRAINT fk3vqwgba2jhvbq2beipspjx1rw FOREIGN KEY (cliente_id) REFERENCES cliente (id),
    CONSTRAINT fk4j4ubn2njo5obix82gy214gck FOREIGN KEY (timesheet_id) REFERENCES timesheet (id)
);
