CREATE TABLE IF NOT EXISTS acconto_movimento (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    utente_id BIGINT NOT NULL,
    mese INTEGER NOT NULL,
    anno INTEGER NOT NULL,
    importo NUMERIC(12, 2) NOT NULL,
    note VARCHAR(500),
    data_movimento DATE NOT NULL,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_acconto_movimento_utente FOREIGN KEY (utente_id) REFERENCES utente (id),
    CONSTRAINT acconto_movimento_mese_check CHECK (mese BETWEEN 1 AND 12),
    CONSTRAINT acconto_movimento_anno_check CHECK (anno >= 2000),
    CONSTRAINT acconto_movimento_importo_check CHECK (importo > 0)
);

CREATE INDEX IF NOT EXISTS idx_acconto_movimento_utente_anno_mese ON acconto_movimento (utente_id, anno, mese);
